import type { JsonValue, ParameterValue, SocketDataType } from "../core/types.js";
import type { BuiltinNodeTypeId, CatalogDomain } from "./scope.js";
import type { NodeDescriptor, ValueSchema, SocketDescriptor } from "./types.js";
import { DEFAULT_COLOR_RAMP } from "./color-ramp.js";
const n=(v:number):ParameterValue=>({kind:"number",value:v}), s=(v:string):ParameterValue=>({kind:"string",value:v}), b=(v:boolean):ParameterValue=>({kind:"boolean",value:v}), v=(x:number,y=x,z=x):ParameterValue=>({kind:"vector",value:[x,y,z]}), c=(r:number,g:number,bl:number,a=1):ParameterValue=>({kind:"color",value:[r,g,bl,a]});
const num=(d:number,minimum?:number,maximum?:number,integer=false):Extract<ValueSchema,{type:"number"}>=>({type:"number",default:n(d),...(minimum===undefined?{}:{minimum}),...(maximum===undefined?{}:{maximum}),...(integer?{integer:true}:{})});
const en=(d:string,values:readonly string[]):ValueSchema=>({type:"string",default:s(d),enum:values});
const input=(key:string,label:string,type:SocketDataType,value?:ValueSchema,max=1,visibleWhen?:SocketDescriptor["visibleWhen"]):SocketDescriptor=>({key,label,direction:"input",dataType:type,accepts:type==="any"?["any"]:[type,"any"],maxIncomingLinks:max,visible:true,...(value?{value}:{}),...(visibleWhen?{visibleWhen}:{})});
const output=(key:string,label:string,type:SocketDataType):SocketDescriptor=>({key,label,direction:"output",dataType:type,accepts:[],maxIncomingLinks:0,visible:true});
function d(typeId:BuiltinNodeTypeId,label:string,sockets:readonly SocketDescriptor[],parameters:Readonly<Record<string,ValueSchema>>={},width=140,role?:NodeDescriptor["role"],muteBypass?:readonly (readonly [string,string])[]):NodeDescriptor{const family=typeId.split(".")[1] as CatalogDomain;return{typeId,version:typeId==="fxnode.shader.color-ramp"||typeId==="fxnode.shader.noise-texture"?2:1,family,role:role??(typeId.endsWith("frame")?"container":typeId.includes("output")?"output":typeId.includes("input")?"input":"operator"),label,defaultWidth:typeId.endsWith("frame")?300:width,sockets,parameters,...(muteBypass?{muteBypass}:{})};}
const color={type:"color",default:c(.8,.8,.8,1),minimum:0,maximum:1} as const;
const vector={type:"vector",default:v(0)} as const;
export const BUILTIN_DESCRIPTORS=[
 d("fxnode.common.frame","Frame",[]),
 d("fxnode.common.reroute","Reroute",[input("input","Input","any"),output("output","Output","any")],{},140,undefined,[["input","output"]]),
 d("fxnode.common.group-input","Group Input",[output("output","Interface","any")],{interfaceName:{type:"string",default:s("Socket")}},180),
 d("fxnode.common.group-output","Group Output",[input("input","Interface","any",undefined,Number.MAX_SAFE_INTEGER)],{interfaceName:{type:"string",default:s("Socket")}},180),
 d("fxnode.shader.value","Value",[output("value","Value","float")],{value:{...num(0),step:1}}),
 d("fxnode.shader.color","Color",[output("color","Color","color")],{color}),
 d("fxnode.shader.math","Math",[input("a","A","float",num(0)),input("b","B","float",num(0)),output("value","Value","float")],{operation:en("add",["add","subtract","multiply","divide","power","minimum","maximum"]),clamp:{type:"boolean",default:b(false)}},180,undefined,[["a","value"]]),
 d("fxnode.shader.vector-math","Vector Math",[input("a","A","vector",vector),input("b","B","vector",vector,1,{parameter:"operation",equals:"add"}),output("vector","Vector","vector"),output("value","Value","float")],{operation:en("add",["add","subtract","multiply","dot-product","length","normalize"])},190,undefined,[["a","vector"]]),
 d("fxnode.shader.mix","Mix",[input("factor","Factor","float",num(.5,0,1)),input("a","A","color",color),input("b","B","color",color),output("result","Result","color")],{blend:en("mix",["mix","add","multiply","screen","overlay"]),clamp:{type:"boolean",default:b(false)}},190,undefined,[["a","result"]]),
 {...d("fxnode.shader.color-ramp","Color Ramp",[input("factor","Factor","float",num(.5,0,1)),output("color","Color","color"),output("alpha","Alpha","float")],{ramp:{type:"color-ramp",default:{kind:"json",value:DEFAULT_COLOR_RAMP as unknown as JsonValue}}},320),ui:[{kind:"socket",key:"color"},{kind:"socket",key:"alpha"},{kind:"parameter",key:"ramp",label:""},{kind:"socket",key:"factor"}]},
 d("fxnode.shader.texture-coordinate","Texture Coordinate",[output("generated","Generated","vector"),output("normal","Normal","vector"),output("uv","UV","vector"),output("object","Object","vector")],{},190),
 {...d("fxnode.shader.noise-texture","Noise Texture",[
   input("vector","Vector","vector",vector,1,{parameter:"dimensions",in:["2d","3d","4d"]}),
   input("w","W","float",num(0),1,{parameter:"dimensions",in:["1d","4d"]}),
   input("scale","Scale","float",num(5,-1000,1000)), input("detail","Detail","float",num(2,0,15)),
   input("roughness","Roughness","float",num(.5,0,1)), input("lacunarity","Lacunarity","float",num(2,0,1000)),
   input("offset","Offset","float",num(0,-1000,1000),1,{parameter:"noiseType",in:["hybrid-multifractal","ridged-multifractal","hetero-terrain"]}),
   input("gain","Gain","float",num(1,0,1000),1,{parameter:"noiseType",in:["hybrid-multifractal","ridged-multifractal"]}),
   input("distortion","Distortion","float",num(0,-1000,1000)), output("factor","Factor","float"), output("color","Color","color")
 ],{dimensions:en("3d",["1d","2d","3d","4d"]),noiseType:en("fbm",["fbm","multifractal","hybrid-multifractal","ridged-multifractal","hetero-terrain"]),normalize:{type:"boolean",default:b(false)}},200),ui:[
   {kind:"parameter",key:"dimensions",label:"Dimensions"},{kind:"parameter",key:"noiseType",label:"Type"},{kind:"parameter",key:"normalize",label:"Normalize",visibleWhen:{parameter:"noiseType",equals:"fbm"}},
   {kind:"socket",key:"vector"},{kind:"socket",key:"w"},{kind:"socket",key:"scale"},{kind:"socket",key:"detail"},{kind:"socket",key:"roughness"},{kind:"socket",key:"lacunarity"},{kind:"socket",key:"offset"},{kind:"socket",key:"gain"},{kind:"socket",key:"distortion"},{kind:"socket",key:"factor"},{kind:"socket",key:"color"}
 ]},
 {...d("fxnode.shader.image-texture","Image Texture",[
   input("vector","Vector","vector",vector),output("color","Color","color"),output("alpha","Alpha","float")
 ],{image:{type:"string",default:s("")},interpolation:en("Linear",["Linear","Closest","Cubic","Smart"]),projection:en("Flat",["Flat","Box","Sphere","Tube"]),blend:num(0,0,1),extension:en("Repeat",["Repeat","Extend","Clip","Mirror"]),colorSpace:en("sRGB",["sRGB","Linear","Non-Color"]),alphaMode:en("Straight",["Straight","Premultiplied","Channel Packed","None"])},280,"input"),ui:[
   {kind:"resource",key:"image",label:"Image",openLabel:"Open",newLabel:"New"},{kind:"parameter",key:"interpolation"},{kind:"parameter",key:"projection"},{kind:"parameter",key:"blend",label:"Blend",visibleWhen:{parameter:"projection",equals:"Box"}},{kind:"parameter",key:"extension"},{kind:"parameter",key:"colorSpace",label:"Color Space"},{kind:"parameter",key:"alphaMode",label:"Alpha Mode"},{kind:"socket",key:"vector"},{kind:"socket",key:"color"},{kind:"socket",key:"alpha"}
 ]},
 d("fxnode.shader.principled-bsdf","Principled BSDF",[input("base-color","Base Color","color",color),input("metallic","Metallic","float",num(0,0,1)),input("roughness","Roughness","float",num(.5,0,1)),input("ior","IOR","float",num(1.5,1,1000)),input("alpha","Alpha","float",num(1,0,1)),input("normal","Normal","vector",vector),output("bsdf","BSDF","shader")],{},220),
 d("fxnode.shader.material-output","Material Output",[input("surface","Surface","shader"),input("volume","Volume","shader"),input("displacement","Displacement","vector",vector)],{},190),
 d("fxnode.geometry.position","Position",[output("position","Position","vector")]),
 d("fxnode.geometry.mesh-cube","Mesh Cube",[input("size","Size","vector",{type:"vector",default:v(1),minimum:0}),input("vertices-x","Vertices X","float",num(2,2,1000,true)),input("vertices-y","Vertices Y","float",num(2,2,1000,true)),input("vertices-z","Vertices Z","float",num(2,2,1000,true)),output("mesh","Mesh","geometry")],{},190),
 d("fxnode.geometry.set-position","Set Position",[input("geometry","Geometry","geometry"),input("position","Position","vector",vector),input("offset","Offset","vector",vector),output("result","Geometry","geometry")],{},190,undefined,[["geometry","result"]]),
 d("fxnode.geometry.transform-geometry","Transform Geometry",[input("geometry","Geometry","geometry"),input("translation","Translation","vector",vector),input("rotation","Rotation","vector",vector),input("scale","Scale","vector",{type:"vector",default:v(1)}),output("result","Geometry","geometry")],{},210,undefined,[["geometry","result"]]),
 d("fxnode.geometry.join-geometry","Join Geometry",[input("geometry","Geometry","geometry",undefined,Number.MAX_SAFE_INTEGER),output("result","Geometry","geometry")],{},180),
 {...d("fxnode.compositor.image","Image",[output("image","Image","color"),output("alpha","Alpha","float"),output("z","Z","float")],{
   image:{type:"string",default:s("")},source:en("File",["Generated","File","Movie","Sequence","Multilayer"]),frames:num(1,1,1048574,true),startFrame:num(1,-1048574,1048574,true),offset:num(0,-1048574,1048574,true),cyclic:{type:"boolean",default:b(false)},autoRefresh:{type:"boolean",default:b(false)}
 },240,"input"),ui:[{kind:"resource",key:"image",label:"Image",openLabel:"Open",newLabel:"New"},{kind:"parameter",key:"source"},{kind:"parameter",key:"frames",label:"Frames",visibleWhen:{parameter:"source",in:["Movie","Sequence"]}},{kind:"parameter",key:"startFrame",label:"Start Frame",visibleWhen:{parameter:"source",in:["Movie","Sequence"]}},{kind:"parameter",key:"offset",visibleWhen:{parameter:"source",in:["Movie","Sequence"]}},{kind:"parameter",key:"cyclic",visibleWhen:{parameter:"source",in:["Movie","Sequence"]}},{kind:"parameter",key:"autoRefresh",label:"Auto Refresh",visibleWhen:{parameter:"source",in:["Movie","Sequence"]}},{kind:"socket",key:"image"},{kind:"socket",key:"alpha"},{kind:"socket",key:"z"}]},
 {...d("fxnode.compositor.color-balance","Color Balance",[input("image","Image","color",color),input("factor","Factor","float",num(1,0,1)),output("result","Image","color")],{
   mode:en("Lift/Gamma/Gain",["Lift/Gamma/Gain","Offset/Power/Slope","White Point"]),lift:num(0),liftColor:{type:"color",default:c(1,1,1)},gamma:num(1),gammaColor:{type:"color",default:c(1,1,1)},gain:num(1),gainColor:{type:"color",default:c(1,1,1)},offset:num(0),offsetColor:{type:"color",default:c(1,1,1)},power:num(1),powerColor:{type:"color",default:c(1,1,1)},slope:num(1),slopeColor:{type:"color",default:c(1,1,1)},inputTemperature:num(6500),inputTint:num(0),inputColor:{type:"color",default:c(1,1,1)},outputTemperature:num(6500),outputTint:num(0),outputColor:{type:"color",default:c(1,1,1)}
 },400,"operator",[["image","result"]]),ui:[
   {kind:"parameter",key:"mode"},
   {kind:"grading-wheels",wheels:[{scalar:"lift",color:"liftColor",label:"Lift"},{scalar:"gamma",color:"gammaColor",label:"Gamma"},{scalar:"gain",color:"gainColor",label:"Gain"}],visibleWhen:{parameter:"mode",equals:"Lift/Gamma/Gain"}},
   {kind:"grading-wheels",wheels:[{scalar:"offset",color:"offsetColor",label:"Offset"},{scalar:"power",color:"powerColor",label:"Power"},{scalar:"slope",color:"slopeColor",label:"Slope"}],visibleWhen:{parameter:"mode",equals:"Offset/Power/Slope"}},
   {kind:"section",label:"Input",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"parameter",key:"inputTemperature",label:"Temperature",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"parameter",key:"inputTint",label:"Tint",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"parameter",key:"inputColor",label:"Color",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"eyedropper",label:"Eyedropper (host bridge)",visibleWhen:{parameter:"mode",equals:"White Point"}},
   {kind:"section",label:"Output",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"parameter",key:"outputTemperature",label:"Temperature",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"parameter",key:"outputTint",label:"Tint",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"parameter",key:"outputColor",label:"Color",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"eyedropper",label:"Eyedropper (host bridge)",visibleWhen:{parameter:"mode",equals:"White Point"}},{kind:"socket",key:"image"},{kind:"socket",key:"factor"},{kind:"socket",key:"result"}
 ]},
] as const satisfies readonly NodeDescriptor[];
