import { BUILTIN_DESCRIPTORS } from "../catalog/descriptors.js";
import type { BuiltinNodeTypeId, CatalogDomain } from "../catalog/scope.js";

interface Point { readonly x:number;readonly y:number }
export interface AddNodeMenu { open(viewPosition:Point):void;close(restoreCanvasFocus?:boolean):void;destroy():void }

const groups:readonly CatalogDomain[]=["common","shader","geometry","compositor"];
const groupLabel=(family:CatalogDomain)=>family[0]!.toUpperCase()+family.slice(1);
const entries=BUILTIN_DESCRIPTORS.map(descriptor=>({typeId:descriptor.typeId,label:descriptor.label,family:descriptor.family,search:`${descriptor.label} ${descriptor.family} ${descriptor.typeId.split(".").at(-1)}`.toLowerCase()}));

export function createAddNodeMenu(canvas:HTMLCanvasElement,onSelect:(typeId:BuiltinNodeTypeId,viewPosition:Point)=>void):AddNodeMenu{
  let host:HTMLDivElement|undefined;
  let removeListeners=()=>{};
  const close=(restore=false)=>{if(!host)return;removeListeners();host.remove();host=undefined;if(restore)canvas.focus();};
  const open=(viewPosition:Point)=>{
    close();
    host=document.createElement("div");host.dataset.fxnodeAddMenu="";host.style.cssText="position:fixed;z-index:2147483647;visibility:hidden";
    const root=host.attachShadow({mode:"open"});
    root.innerHTML=`<style>:host{all:initial}*{box-sizing:border-box}.dialog{width:286px;max-height:min(520px,calc(100vh - 16px));display:flex;flex-direction:column;padding:8px;background:#25282d;color:#e5e5e5;border:1px solid #111216;border-radius:7px;box-shadow:0 12px 32px #000a;font:12px/1.3 system-ui,sans-serif}.title{font-weight:650;margin:1px 2px 7px}.search{width:100%;border:1px solid #111216;border-radius:4px;background:#181a1e;color:#fff;padding:7px 8px;outline:none}.search:focus{border-color:#ed5700}.results{overflow:auto;margin-top:7px;min-height:40px}.group{margin:4px 0 7px}.heading{padding:3px 7px;color:#a5a8ad;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.07em}.option{display:block;width:100%;padding:6px 8px;border:0;border-radius:4px;background:transparent;color:#e5e5e5;text-align:left;font:inherit;cursor:default}.option:hover,.option.active{background:#ed5700;color:#fff}.empty{padding:14px 8px;color:#a5a8ad;text-align:center}</style><section class="dialog" role="dialog" aria-label="Add node"><div class="title">Add Node</div><input class="search" type="search" role="combobox" aria-label="Search nodes" aria-autocomplete="list" aria-controls="fxnode-node-results" autocomplete="off" placeholder="Search…"><div class="results" id="fxnode-node-results" role="listbox"></div></section>`;
    const input=root.querySelector<HTMLInputElement>(".search")!,results=root.querySelector<HTMLDivElement>(".results")!;let visible=entries.slice(),active=0;
    const choose=(index:number)=>{const item=visible[index];if(!item)return;close(true);onSelect(item.typeId,viewPosition);};
    const render=()=>{results.replaceChildren();let optionIndex=0;for(const family of groups){const familyEntries=visible.filter(item=>item.family===family);if(!familyEntries.length)continue;const group=document.createElement("div");group.className="group";group.setAttribute("role","group");group.setAttribute("aria-label",groupLabel(family));const heading=document.createElement("div");heading.className="heading";heading.textContent=groupLabel(family);group.append(heading);for(const item of familyEntries){const index=optionIndex++,button=document.createElement("button");button.type="button";button.className=`option${index===active?" active":""}`;button.id=`fxnode-node-option-${index}`;button.setAttribute("role","option");button.setAttribute("aria-selected",String(index===active));button.textContent=item.label;button.addEventListener("pointerenter",()=>{if(active!==index){active=index;render();}});button.addEventListener("click",()=>choose(index));group.append(button);}results.append(group);}if(!visible.length){const empty=document.createElement("div");empty.className="empty";empty.setAttribute("role","status");empty.textContent="No nodes found";results.append(empty);}input.setAttribute("aria-expanded","true");input.setAttribute("aria-activedescendant",visible.length?`fxnode-node-option-${active}`:"");};
    input.addEventListener("input",()=>{const query=input.value.trim().toLowerCase();visible=entries.filter(item=>!query||item.search.includes(query));active=0;render();});
    input.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();close(true);return;}if(!visible.length)return;if(event.key==="ArrowDown"||event.key==="ArrowUp"||event.key==="Home"||event.key==="End"){event.preventDefault();active=event.key==="Home"?0:event.key==="End"?visible.length-1:(active+(event.key==="ArrowDown"?1:-1)+visible.length)%visible.length;render();root.getElementById(`fxnode-node-option-${active}`)?.scrollIntoView({block:"nearest"});}else if(event.key==="Enter"){event.preventDefault();choose(active);}});
    render();document.body.append(host);const rect=canvas.getBoundingClientRect(),menu=host.getBoundingClientRect(),margin=8;host.style.left=`${Math.max(margin,Math.min(rect.left+viewPosition.x,window.innerWidth-menu.width-margin))}px`;host.style.top=`${Math.max(margin,Math.min(rect.top+viewPosition.y,window.innerHeight-menu.height-margin))}px`;host.style.visibility="visible";input.focus();
    const outside=(event:PointerEvent)=>{if(host&&!event.composedPath().includes(host))close(false);},blur=()=>close(false),scroll=()=>close(false);document.addEventListener("pointerdown",outside,true);window.addEventListener("blur",blur);window.addEventListener("scroll",scroll,true);removeListeners=()=>{document.removeEventListener("pointerdown",outside,true);window.removeEventListener("blur",blur);window.removeEventListener("scroll",scroll,true);removeListeners=()=>{};};
  };
  return{open,close,destroy:()=>close(false)};
}
